<?php
declare(strict_types=1);
final class Admin {
    public function __construct(private Database $db,private AuditLog $audit,private RateLimiter $rate,private TelegramClient $telegram,private array $config) {}
    private static function e(mixed $v):string{return htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');}
    private function session():void {if(session_status()===PHP_SESSION_ACTIVE)return;session_set_cookie_params(['httponly'=>true,'secure'=>((($_SERVER['HTTPS']??'')==='on')),'samesite'=>'Lax','path'=>'/']);session_name('faceunlock_admin');session_start();}
    private function bearer():bool{$token=Util::bearer();$hash=(string)($this->config['admin']['token_hash']??'');return $token!==null&&$hash!==''&&hash_equals($hash,hash('sha256',$token));}
    private function authenticated():bool{$this->session();if($this->bearer())return true;$until=(int)($_SESSION['admin_until']??0);return $until>=time();}
    private function csrf():string{$this->session();return $_SESSION['csrf']??=Util::token();}
    private function requireAuth():void{if($this->authenticated())return;header('Location: /admin/login',true,302);exit;}
    private function requireCsrf():void{if(!hash_equals((string)($_SESSION['csrf']??''),(string)($_POST['csrf']??''))){http_response_code(403);exit('CSRF validation failed');}}
    private function page(string $title,string $body):never{header('Content-Type: text/html; charset=utf-8');header('Cache-Control: no-store');header('X-Content-Type-Options: nosniff');header('Referrer-Policy: no-referrer');header("Content-Security-Policy: default-src 'self'; style-src 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");$nav='<nav><a href="/admin">Dashboard</a><a href="/admin/pcs">PCs</a><a href="/admin/devices">iPhones</a><a href="/admin/pairings">Pairings</a><a href="/admin/unlocks">Unlocks</a><a href="/admin/audit">Audit</a><a href="/admin/health">Health</a><form method="post" action="/admin/logout"><input type="hidden" name="csrf" value="'.$this->e($this->csrf()).'"><button>Logout</button></form></nav>';$css='body{font:15px system-ui;margin:0;background:#101827;color:#e5e7eb}nav{display:flex;gap:14px;align-items:center;padding:15px;background:#182235;flex-wrap:wrap}a{color:#93c5fd;text-decoration:none}nav form{margin-left:auto}main{max-width:1200px;margin:auto;padding:24px}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:12px}.card,table{background:#182235;border-radius:8px;padding:14px}.n{font-size:28px;font-weight:bold}table{width:100%;border-collapse:collapse;padding:0}td,th{padding:10px;border-bottom:1px solid #334155;text-align:left}.ACTIVE,.APPROVED{color:#86efac}.REVOKED,.REJECTED,.EXPIRED{color:#fca5a5}.PENDING{color:#fde68a}input,button,select{padding:8px;border-radius:5px;border:1px solid #475569;background:#0f172a;color:#fff}.msg{padding:10px;background:#1e3a5f;border-radius:6px}';echo '<!doctype html><html><head><meta name="viewport" content="width=device-width"><title>'.self::e($title).'</title><style>'.$css.'</style></head><body>'.$nav.'<main><h1>'.self::e($title).'</h1>'.$body.'</main></body></html>';exit;}
    private function rows(string $sql,array $params=[]):array{$s=$this->db->pdo->prepare($sql);$s->execute($params);return $s->fetchAll();}
    private function table(array $rows,array $columns):string{$out='<table><tr>';foreach($columns as $label=>$key)$out.='<th>'.self::e($label).'</th>';$out.='</tr>';foreach($rows as$r){$out.='<tr>';foreach($columns as$key)$out.='<td>'.self::e($r[$key]??'—').'</td>';$out.='</tr>';}$out.='</table>';return $out;}
    private function pager(string $base,int $page):string{return '<p><a href="'.$base.'?page='.max(1,$page-1).'">← Previous</a> · <a href="'.$base.'?page='.($page+1).'">Next →</a></p>';}
    private function pageNo():array{$p=max(1,(int)($_GET['page']??1));return[$p,min(100,max(1,(int)($_GET['limit']??25))),($p-1)*min(100,max(1,(int)($_GET['limit']??25)))];}
    public function handle(string $method,string $path):never {
      if($path==='/admin/login'&&$method==='GET'){echo '<!doctype html><title>FaceUnlock Admin</title><form method="post"><h1>FaceUnlock Admin</h1><label>Admin Token <input type="password" name="token" autofocus required></label><button>Login</button></form>';exit;}
      if($path==='/admin/login'&&$method==='POST'){$this->rate->check('admin_login');$hash=(string)($this->config['admin']['token_hash']??'');$ok=$hash!==''&&hash_equals($hash,hash('sha256',(string)($_POST['token']??'')));if(!$ok){$this->audit->write('ADMIN_LOGIN_FAILED','DENIED');http_response_code(401);exit('Invalid credentials.');}$this->session();session_regenerate_id(true);$_SESSION['admin_until']=time()+(int)($this->config['admin']['session_ttl']??3600);$_SESSION['csrf']=Util::token();$this->audit->write('ADMIN_LOGIN_SUCCESS','OK');header('Location: /admin');exit;}
      if($path==='/admin/logout'&&$method==='POST'){$this->requireAuth();$this->requireCsrf();$this->audit->write('ADMIN_LOGOUT','OK');$_SESSION=[];session_destroy();header('Location: /admin/login');exit;}
      $this->requireAuth();$this->audit->write('ADMIN_VIEW','OK',null,null,null,['page'=>$path]);
      if($path==='/admin/telegram-test'&&$method==='POST'){$this->requireCsrf();$this->rate->check('admin_telegram_test');try{$this->telegram->sendAdminTest();$this->audit->write('ADMIN_TELEGRAM_TEST','OK');header('Location: /admin/health?telegram=sent');}catch(Throwable){$this->audit->write('ADMIN_TELEGRAM_TEST','ERROR');header('Location: /admin/health?telegram=failed');}exit;}
      if($path==='/admin/api/status'){Util::out(['ok'=>true,'status'=>'healthy','schema_version'=>$this->db->one('SELECT MAX(version) v FROM schema_migrations')['v']??null]);}
      if($path==='/admin' || $path==='/admin/health'){$stats=['PCs'=>(int)($this->db->one('SELECT COUNT(*) n FROM pcs')['n']??0),'iPhones'=>(int)($this->db->one('SELECT COUNT(*) n FROM devices')['n']??0),'Active pairings'=>(int)($this->db->one("SELECT COUNT(*) n FROM pc_device_pairings WHERE status='ACTIVE'")['n']??0),'Pending unlocks'=>(int)($this->db->one("SELECT COUNT(*) n FROM unlock_requests WHERE status='PENDING'")['n']??0),'Approved today'=>(int)($this->db->one("SELECT COUNT(*) n FROM unlock_requests WHERE status='APPROVED' AND approved_at>=CURDATE()")['n']??0)];$cards='<div class="cards">';foreach($stats as$k=>$v)$cards.='<div class="card"><div>'.$k.'</div><div class="n">'.$v.'</div></div>';$cards.='</div><p class="msg">Database: PASS · HTTPS: '.((($_SERVER['HTTPS']??'')==='on')?'PASS':'WARN').' · Telegram: '.(!empty($this->config['telegram']['bot_token'])?'CONFIGURED':'DISABLED').' · Schema: '.self::e($this->db->one('SELECT MAX(version) v FROM schema_migrations')['v']??'unknown').'</p><form method="post" action="/admin/telegram-test"><input type="hidden" name="csrf" value="'.$this->e($this->csrf()).'"><button>Send Telegram test</button></form>';$this->page($path==='/admin'?'Dashboard':'Health',$cards);}
      [$page,$limit,$offset]=$this->pageNo(); if($path==='/admin/pcs'){$q='%'.(string)($_GET['q']??'').'%';$rows=$this->rows("SELECT p.id,p.name,p.last_seen_at,COUNT(x.device_id) paired_iphones,SUM(x.status='ACTIVE') active_pairings FROM pcs p LEFT JOIN pc_device_pairings x ON x.pc_id=p.id WHERE p.name LIKE ? OR p.id LIKE ? GROUP BY p.id ORDER BY p.created_at DESC LIMIT $limit OFFSET $offset",[$q,$q]);$this->page('PC management',$this->table($rows,['Name'=>'name','ID'=>'id','Paired iPhones'=>'paired_iphones','Active'=>'active_pairings','Last seen'=>'last_seen_at']).$this->pager('/admin/pcs',$page));}
      if($path==='/admin/devices'){$q='%'.(string)($_GET['q']??'').'%';$rows=$this->rows("SELECT d.id,d.name,d.last_seen_at,COUNT(x.pc_id) paired_pcs,SUM(x.status='ACTIVE') active_pairings FROM devices d LEFT JOIN pc_device_pairings x ON x.device_id=d.id WHERE d.name LIKE ? OR d.id LIKE ? GROUP BY d.id ORDER BY d.created_at DESC LIMIT $limit OFFSET $offset",[$q,$q]);$this->page('iPhone management',$this->table($rows,['Name'=>'name','ID'=>'id','Paired PCs'=>'paired_pcs','Active'=>'active_pairings','Last seen'=>'last_seen_at']).$this->pager('/admin/devices',$page));}
      if($path==='/admin/pairings'){$status=(string)($_GET['status']??'');$rows=$this->rows("SELECT x.pc_id,x.device_id,p.name pc_name,d.name device_name,x.status,x.nickname,x.paired_at,x.last_used_at,x.revoked_at FROM pc_device_pairings x JOIN pcs p ON p.id=x.pc_id JOIN devices d ON d.id=x.device_id WHERE (?='' OR x.status=?) ORDER BY x.updated_at DESC LIMIT $limit OFFSET $offset",[$status,$status]);$form='<form method="post" action="/admin/pairings/action"><input type="hidden" name="csrf" value="'.$this->e($this->csrf()).'"><input name="pc_id" placeholder="PC ID"><input name="device_id" placeholder="Device ID"><input name="nickname" placeholder="Nickname"><button name="action" value="rename">Rename</button><button name="action" value="revoke">Revoke</button><button name="action" value="reactivate">Reactivate</button></form>';$this->page('Pairing management',$form.$this->table($rows,['PC'=>'pc_name','iPhone'=>'device_name','Status'=>'status','Nickname'=>'nickname','Paired'=>'paired_at','Last used'=>'last_used_at','Revoked'=>'revoked_at']).$this->pager('/admin/pairings',$page));}
      if($path==='/admin/pairings/action'&&$method==='POST'){$this->requireCsrf();$pc=(string)$_POST['pc_id'];$dev=(string)$_POST['device_id'];$action=(string)$_POST['action'];if(!Util::validId($pc)||!Util::validId($dev)){http_response_code(400);exit('Invalid pairing');}if($action==='revoke')$this->db->exec("UPDATE pc_device_pairings SET status='REVOKED',revoked_at=NOW() WHERE pc_id=? AND device_id=?",[$pc,$dev]);elseif($action==='reactivate')$this->db->exec("UPDATE pc_device_pairings SET status='ACTIVE',revoked_at=NULL WHERE pc_id=? AND device_id=?",[$pc,$dev]);elseif($action==='rename')$this->db->exec('UPDATE pc_device_pairings SET nickname=? WHERE pc_id=? AND device_id=?',[mb_substr((string)$_POST['nickname'],0,255),$pc,$dev]);else {http_response_code(400);exit('Invalid action');}$this->audit->write($action==='revoke'?'ADMIN_REVOKE_PAIRING':'ADMIN_RENAME_PAIRING','OK',$pc,$dev);header('Location: /admin/pairings');exit;}
      if($path==='/admin/unlocks'){$rows=$this->rows("SELECT r.id,p.name pc_name,r.status,r.winning_device_id,r.winning_transport,r.created_at,r.expires_at,r.approved_at,COUNT(c.device_id) candidate_count FROM unlock_requests r JOIN pcs p ON p.id=r.pc_id LEFT JOIN unlock_request_candidates c ON c.request_id=r.id GROUP BY r.id ORDER BY r.created_at DESC LIMIT $limit OFFSET $offset");$this->page('Unlock requests',$this->table($rows,['Request'=>'id','PC'=>'pc_name','Status'=>'status','Candidates'=>'candidate_count','Winner'=>'winning_device_id','Transport'=>'winning_transport','Created'=>'created_at','Approved'=>'approved_at']).$this->pager('/admin/unlocks',$page));}
      if($path==='/admin/audit'){$event='%'.(string)($_GET['event']??'').'%';$rows=$this->rows("SELECT occurred_at,event,result,pc_id,device_id,request_id,ip_hash,metadata_json FROM security_audit_log WHERE event LIKE ? ORDER BY occurred_at DESC LIMIT $limit OFFSET $offset",[$event]);$this->page('Security audit',$this->table($rows,['Time'=>'occurred_at','Event'=>'event','Result'=>'result','PC'=>'pc_id','Device'=>'device_id','Request'=>'request_id','IP hash'=>'ip_hash','Metadata'=>'metadata_json']).$this->pager('/admin/audit',$page));}
      http_response_code(404);$this->page('Not found','<p>Unknown admin page.</p>');
    }
}
