using System.Diagnostics;
using System.Management;
using System.Net.Http.Json;
using System.Runtime.InteropServices;
using FaceUnlock.Core;

namespace FaceUnlock.Service;

public sealed class RemoteControlWorker : BackgroundService {
 private readonly ILogger<RemoteControlWorker> _log; private readonly ConfigStore _store=new(); private DateTime _lastTempAlert=DateTime.MinValue,_lastRamAlert=DateTime.MinValue;
 public RemoteControlWorker(ILogger<RemoteControlWorker> log)=>_log=log;
 protected override async Task ExecuteAsync(CancellationToken stop){while(!stop.IsCancellationRequested){try{var cfg=_store.Load();if(!string.IsNullOrWhiteSpace(cfg.PcToken)){await CheckAlerts(cfg,stop);var api=new ApiClient(cfg);var p=await api.GetRemoteCommandAsync(stop);if(p.pending&&p.command!=null)await Handle(api,p.command,cfg,stop);}}catch(OperationCanceledException)when(stop.IsCancellationRequested){break;}catch(Exception e){_log.LogDebug(e,"Remote control poll skipped");}await Task.Delay(TimeSpan.FromSeconds(3),stop);}}
 private async Task Handle(ApiClient api,RemoteCommand c,LocalConfig cfg,CancellationToken ct){try{object result=c.type switch{
  "status"=>ReadStatus(), "lock"=>Lock(), "restart"=>Power("/r /t 1"), "shutdown"=>Power("/s /t 1"), "apps"=>Apps(), "close_app"=>CloseApp(c.payload),
  "clipboard_set"=>ClipboardSet(c.payload), "clipboard_get"=>ClipboardGet(), "file_upload"=>FileUpload(c.payload), "clipboard_file_download"=>ClipboardFile(), "screenshot"=>Screenshot(),
  _=>throw new InvalidOperationException("Unsupported command")}; await api.CompleteRemoteCommandAsync(c.id,"DONE",result,ct);}catch(Exception e){await api.CompleteRemoteCommandAsync(c.id,"ERROR",new{error=e.Message},ct);}}
 private static object ReadStatus(){var cpu=0d;try{using var s=new ManagementObjectSearcher("SELECT LoadPercentage FROM Win32_Processor");var vals=s.Get().Cast<ManagementObject>().Select(x=>Convert.ToDouble(x["LoadPercentage"]));cpu=vals.Any()?vals.Average():0;}catch{} var ram=RamPercent();return new{cpu_percent=Math.Round(cpu,1),ram_percent=Math.Round(ram,1),temperature_c=CpuTemperature()};}
 private static double RamPercent(){try{using var s=new ManagementObjectSearcher("SELECT TotalVisibleMemorySize,FreePhysicalMemory FROM Win32_OperatingSystem");var o=s.Get().Cast<ManagementObject>().First();var total=Convert.ToDouble(o["TotalVisibleMemorySize"]);var free=Convert.ToDouble(o["FreePhysicalMemory"]);return total>0?(total-free)*100/total:0;}catch{return 0;}}
 private static double? CpuTemperature(){try{using var s=new ManagementObjectSearcher(@"root\WMI","SELECT CurrentTemperature FROM MSAcpi_ThermalZoneTemperature");var v=s.Get().Cast<ManagementObject>().Select(x=>(Convert.ToDouble(x["CurrentTemperature"])/10)-273.15).Where(x=>x>0&&x<150).ToArray();return v.Length>0?Math.Round(v.Max(),1):null;}catch{return null;}}
 [DllImport("user32.dll")] private static extern bool LockWorkStation(); private static object Lock(){if(!LockWorkStation())throw new InvalidOperationException("LockWorkStation failed");return new{locked=true};}
 private static object Power(string args){Process.Start(new ProcessStartInfo("shutdown.exe",args){UseShellExecute=false,CreateNoWindow=true});return new{accepted=true};}
 private static object Apps()=>new{apps=Process.GetProcesses().Where(p=>{try{return !string.IsNullOrWhiteSpace(p.MainWindowTitle);}catch{return false;}}).Select(p=>new{id=p.Id,name=p.ProcessName,title=SafeTitle(p)}).OrderBy(x=>x.name).Take(200).ToArray()};
 private static string SafeTitle(Process p){try{return p.MainWindowTitle;}catch{return "";}}
 private static object CloseApp(Dictionary<string,object>? p){if(p==null||!p.TryGetValue("pid",out var raw)||!int.TryParse(raw?.ToString(),out var pid))throw new InvalidOperationException("pid required");using var proc=Process.GetProcessById(pid);if(!proc.CloseMainWindow()){proc.Kill(true);}return new{closed=true,pid};}
 private static object ClipboardSet(Dictionary<string,object>? p){var text=p!=null&&p.TryGetValue("text",out var v)?v?.ToString()??"":"";var f=Path.Combine(Path.GetTempPath(),"faceunlock-clipboard-in.txt");File.WriteAllText(f,text);return new{queued=true,bridge_file=f,note="Interactive clipboard bridge consumes this file when Agent is open"};}
 private static object ClipboardGet(){var f=Path.Combine(Path.GetTempPath(),"faceunlock-clipboard-out.txt");return new{text=File.Exists(f)?File.ReadAllText(f):"",available=File.Exists(f)};}
 private static object FileUpload(Dictionary<string,object>? p){if(p==null||!p.TryGetValue("name",out var n)||!p.TryGetValue("base64",out var b))throw new InvalidOperationException("name/base64 required");var name=Path.GetFileName(n?.ToString()??"upload.bin");var data=Convert.FromBase64String(b?.ToString()??"");if(data.Length>8*1024*1024)throw new InvalidOperationException("File exceeds 8 MB remote relay limit");var dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),"FaceUnlock","Incoming");Directory.CreateDirectory(dir);var path=Path.Combine(dir,name);File.WriteAllBytes(path,data);return new{saved=true,name,size=data.Length,path};}
 private static object ClipboardFile(){var f=Path.Combine(Path.GetTempPath(),"faceunlock-file-out.path");if(!File.Exists(f))return new{available=false};var path=File.ReadAllText(f).Trim();if(!File.Exists(path))return new{available=false};var data=File.ReadAllBytes(path);if(data.Length>8*1024*1024)throw new InvalidOperationException("File exceeds 8 MB remote relay limit");return new{available=true,name=Path.GetFileName(path),base64=Convert.ToBase64String(data),size=data.Length};}
 private static object Screenshot(){var f=Path.Combine(Path.GetTempPath(),"faceunlock-screenshot.jpg");if(!File.Exists(f))return new{available=false,note="Open FaceUnlock Agent once to enable interactive screenshot bridge"};var data=File.ReadAllBytes(f);return new{available=true,mime="image/jpeg",base64=Convert.ToBase64String(data)};}
 private async Task CheckAlerts(LocalConfig c,CancellationToken ct){var now=DateTime.UtcNow;var ram=RamPercent();var temp=CpuTemperature();if(c.RamAlertEnabled&&ram>=c.RamAlertPercent&&(now-_lastRamAlert).TotalSeconds>=c.AlertCooldownSeconds){_lastRamAlert=now;await Telegram(c,$"⚠️ FaceUnlock RAM alert\nPC: {c.PcName}\nRAM: {ram:F1}% (limit {c.RamAlertPercent:F0}%)",ct);}if(c.TemperatureAlertEnabled&&temp.HasValue&&temp.Value>=c.TemperatureAlertCelsius&&(now-_lastTempAlert).TotalSeconds>=c.AlertCooldownSeconds){_lastTempAlert=now;await Telegram(c,$"🔥 FaceUnlock temperature alert\nPC: {c.PcName}\nCPU: {temp:F1}°C (limit {c.TemperatureAlertCelsius:F0}°C)",ct);}}
 private static async Task Telegram(LocalConfig c,string text,CancellationToken ct){if(string.IsNullOrWhiteSpace(c.TelegramBotToken)||string.IsNullOrWhiteSpace(c.TelegramChatId))return;using var h=new HttpClient();await h.PostAsJsonAsync($"https://api.telegram.org/bot{c.TelegramBotToken}/sendMessage",new{chat_id=c.TelegramChatId,text},ct);}
}
