using System.Diagnostics;
using System.Management;
using System.Net.Http.Json;
using System.Runtime.InteropServices;
using FaceUnlock.Core;
namespace FaceUnlock.Service;
public sealed class RemoteControlWorker:BackgroundService{
 readonly ILogger<RemoteControlWorker> _log;readonly ConfigStore _store=new();DateTime _lastTempAlert=DateTime.MinValue,_lastRamAlert=DateTime.MinValue;static readonly string BridgeDir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),"FaceUnlock","Bridge");static string Bridge(string n){Directory.CreateDirectory(BridgeDir);return Path.Combine(BridgeDir,n);}public RemoteControlWorker(ILogger<RemoteControlWorker> log)=>_log=log;
 protected override async Task ExecuteAsync(CancellationToken stop){while(!stop.IsCancellationRequested){try{var cfg=_store.Load();if(!string.IsNullOrWhiteSpace(cfg.PcToken)){await CheckAlerts(cfg,stop);var api=new ApiClient(cfg);var p=await api.GetRemoteCommandAsync(stop);if(p.pending&&p.command!=null)await Handle(api,p.command,cfg,stop);}}catch(OperationCanceledException)when(stop.IsCancellationRequested){break;}catch(Exception e){_log.LogDebug(e,"Remote control poll skipped");}await Task.Delay(3000,stop);}}
 async Task Handle(ApiClient api,RemoteCommand c,LocalConfig cfg,CancellationToken ct){try{object result=c.type switch{"status"=>ReadStatus(),"lock"=>Lock(),"restart"=>Power("/r /t 1"),"shutdown"=>Power("/s /t 1"),"apps"=>Apps(),"close_app"=>CloseApp(c.payload),"clipboard_set"=>ClipboardSet(c.payload),"clipboard_get"=>ClipboardGet(),"file_upload"=>FileUpload(c.payload),"clipboard_file_download"=>ClipboardFile(),"screenshot"=>Screenshot(),_=>throw new InvalidOperationException("Unsupported command")};await api.CompleteRemoteCommandAsync(c.id,"DONE",result,ct);}catch(Exception e){await api.CompleteRemoteCommandAsync(c.id,"ERROR",new{error=e.Message},ct);}}
 static object ReadStatus(){double cpu=0;try{using var s=new ManagementObjectSearcher("SELECT LoadPercentage FROM Win32_Processor");var v=s.Get().Cast<ManagementObject>().Select(x=>Convert.ToDouble(x["LoadPercentage"])).ToArray();if(v.Length>0)cpu=v.Average();}catch{}return new{cpu_percent=Math.Round(cpu,1),ram_percent=Math.Round(RamPercent(),1),temperature_c=CpuTemperature()};}
 static double RamPercent(){try{using var s=new ManagementObjectSearcher("SELECT TotalVisibleMemorySize,FreePhysicalMemory FROM Win32_OperatingSystem");var o=s.Get().Cast<ManagementObject>().First();var t=Convert.ToDouble(o["TotalVisibleMemorySize"]);var f=Convert.ToDouble(o["FreePhysicalMemory"]);return t>0?(t-f)*100/t:0;}catch{return 0;}}
 static double? CpuTemperature(){try{using var s=new ManagementObjectSearcher(@"root\WMI","SELECT CurrentTemperature FROM MSAcpi_ThermalZoneTemperature");var v=s.Get().Cast<ManagementObject>().Select(x=>(Convert.ToDouble(x["CurrentTemperature"])/10)-273.15).Where(x=>x>0&&x<150).ToArray();return v.Length>0?Math.Round(v.Max(),1):null;}catch{return null;}}
 [DllImport("kernel32.dll")]static extern uint WTSGetActiveConsoleSessionId();[DllImport("wtsapi32.dll",SetLastError=true)]static extern bool WTSDisconnectSession(IntPtr hServer,uint sessionId,bool wait);static object Lock(){var id=WTSGetActiveConsoleSessionId();if(id==0xFFFFFFFF||!WTSDisconnectSession(IntPtr.Zero,id,false))throw new InvalidOperationException("Could not lock active console session");return new{locked=true};}
 static object Power(string a){Process.Start(new ProcessStartInfo("shutdown.exe",a){UseShellExecute=false,CreateNoWindow=true});return new{accepted=true};}
 static object Apps()=>new{apps=Process.GetProcesses().Where(p=>{try{return !string.IsNullOrWhiteSpace(p.MainWindowTitle);}catch{return false;}}).Select(p=>new{id=p.Id,name=p.ProcessName,title=SafeTitle(p)}).OrderBy(x=>x.name).Take(200).ToArray()};static string SafeTitle(Process p){try{return p.MainWindowTitle;}catch{return"";}}
 static object CloseApp(Dictionary<string,object>? p){if(p==null||!p.TryGetValue("pid",out var r)||!int.TryParse(r?.ToString(),out var pid))throw new InvalidOperationException("pid required");using var x=Process.GetProcessById(pid);if(!x.CloseMainWindow())x.Kill(true);return new{closed=true,pid};}
 static object ClipboardSet(Dictionary<string,object>? p){var text=p!=null&&p.TryGetValue("text",out var v)?v?.ToString()??"":"";File.WriteAllText(Bridge("clipboard-in.txt"),text);return new{queued=true};}static object ClipboardGet(){var f=Bridge("clipboard-out.txt");return new{text=File.Exists(f)?File.ReadAllText(f):"",available=File.Exists(f)};}
 static object FileUpload(Dictionary<string,object>? p){if(p==null||!p.TryGetValue("name",out var n)||!p.TryGetValue("base64",out var b))throw new InvalidOperationException("name/base64 required");var name=Path.GetFileName(n?.ToString()??"upload.bin");var data=Convert.FromBase64String(b?.ToString()??"");if(data.Length>8*1024*1024)throw new InvalidOperationException("File exceeds 8 MB remote relay limit");var dir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData),"FaceUnlock","Incoming");Directory.CreateDirectory(dir);var path=Path.Combine(dir,name);File.WriteAllBytes(path,data);File.WriteAllText(Bridge("incoming-file.path"),path);return new{saved=true,name,size=data.Length};}
 static object ClipboardFile(){var f=Bridge("clipboard-file.path");if(!File.Exists(f))return new{available=false};var path=File.ReadAllText(f).Trim();if(!File.Exists(path))return new{available=false};var data=File.ReadAllBytes(path);if(data.Length>8*1024*1024)throw new InvalidOperationException("File exceeds 8 MB remote relay limit");return new{available=true,name=Path.GetFileName(path),base64=Convert.ToBase64String(data),size=data.Length};}
 static object Screenshot(){var req=Bridge("screenshot.request");var f=Bridge("screenshot.jpg");if(File.Exists(f))File.Delete(f);File.WriteAllText(req,DateTime.UtcNow.Ticks.ToString());for(var i=0;i<30&&!File.Exists(f);i++)Thread.Sleep(100);if(!File.Exists(f))return new{available=false,error="FaceUnlock Agent interactive bridge is not running"};var d=File.ReadAllBytes(f);return new{available=true,mime="image/jpeg",base64=Convert.ToBase64String(d)};}
 async Task CheckAlerts(LocalConfig c,CancellationToken ct){var now=DateTime.UtcNow,ram=RamPercent();var temp=CpuTemperature();if(c.RamAlertEnabled&&ram>=c.RamAlertPercent&&(now-_lastRamAlert).TotalSeconds>=c.AlertCooldownSeconds){_lastRamAlert=now;await Telegram(c,$"⚠️ FaceUnlock RAM alert\nPC: {c.PcName}\nRAM: {ram:F1}% (limit {c.RamAlertPercent:F0}%)",ct);}if(c.TemperatureAlertEnabled&&temp.HasValue&&temp.Value>=c.TemperatureAlertCelsius&&(now-_lastTempAlert).TotalSeconds>=c.AlertCooldownSeconds){_lastTempAlert=now;await Telegram(c,$"🔥 FaceUnlock temperature alert\nPC: {c.PcName}\nCPU: {temp:F1}°C (limit {c.TemperatureAlertCelsius:F0}°C)",ct);}}
 static async Task Telegram(LocalConfig c,string text,CancellationToken ct){if(string.IsNullOrWhiteSpace(c.TelegramBotToken)||string.IsNullOrWhiteSpace(c.TelegramChatId))return;using var h=new HttpClient();await h.PostAsJsonAsync($"https://api.telegram.org/bot{c.TelegramBotToken}/sendMessage",new{chat_id=c.TelegramChatId,text},ct);}
}
