<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net8.0-windows10.0.26100.0</TargetFramework><UseWPF>true</UseWPF><UseWindowsForms>true</UseWindowsForms></PropertyGroup>
  <ItemGroup><ProjectReference Include="..\FaceUnlock.Core\FaceUnlock.Core.csproj"/><PackageReference Include="QRCoder" Version="1.8.0" /><PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.1" /><PackageReference Include="System.Drawing.Common" Version="8.0.0" /></ItemGroup>
</Project>
