<?php
declare(strict_types=1);
$configPath=dirname(__DIR__).'/config.php'; if(!is_file($configPath)){http_response_code(500);exit('Missing hosting/config.php');}$config=require $configPath;
foreach(['Util','Database','Auth'] as $f) require dirname(__DIR__).'/src/'.$f.'.php';
$db=new Database($config['db']);$auth=new Auth($db);$method=$_SERVER['REQUEST_METHOD'];$path=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH)?:'/';if(($i=strpos($path,'/v1/files/'))!==false)$path=substr($path,$i);
function transferPath(string $stored):string{return dirname(__DIR__).'/storage/transfers/'.basename($stored);}
function paired(Database $db,string $pc,string $dev):bool{return (bool)$db->one("SELECT id FROM pc_device_pairings WHERE pc_id=? AND device_id=? AND status='ACTIVE'",[$pc,$dev]);}
if($method==='GET'&&$path==='/v1/files/list'){$dev=$auth->device();$pc=(string)($_GET['pc_id']??'');if(!$pc||!paired($db,$pc,$dev['id']))Util::error('PAIRING_NOT_FOUND',404);$rows=$db->all("SELECT id,original_name AS name,size_bytes AS size,mime_type AS mime,created_at FROM transfer_files WHERE pc_id=? AND direction='PC_TO_IPHONE' AND status='READY' ORDER BY created_at DESC",[$pc]);Util::out(['ok'=>true,'files'=>$rows]);}
if($method==='DELETE'&&preg_match('#^/v1/files/([^/]+)$#',$path,$m)){$dev=$auth->device();$r=$db->one("SELECT * FROM transfer_files WHERE id=? AND direction='PC_TO_IPHONE' AND status='READY'",[$m[1]]);if(!$r||!paired($db,$r['pc_id'],$dev['id']))Util::error('NOT_FOUND',404);@unlink(transferPath($r['stored_name']));$db->exec("DELETE FROM transfer_files WHERE id=?",[$r['id']]);Util::out(['ok'=>true]);}
if($method==='GET'&&preg_match('#^/v1/files/download/([^/]+)$#',$path,$m)){$dev=$auth->device();$r=$db->one("SELECT * FROM transfer_files WHERE id=? AND direction='PC_TO_IPHONE' AND status='READY'",[$m[1]]);if(!$r||!paired($db,$r['pc_id'],$dev['id'])){http_response_code(404);exit;}$f=transferPath($r['stored_name']);if(!is_file($f)){http_response_code(404);exit;}header('Content-Type: '.($r['mime_type']?:'application/octet-stream'));header('Content-Length: '.filesize($f));header('Content-Disposition: attachment; filename="'.addcslashes($r['original_name'],'"\\').'"');readfile($f);@unlink($f);$db->exec("DELETE FROM transfer_files WHERE id=?",[$r['id']]);exit;}
if($method==='GET'&&$path==='/v1/files/pending'){$pc=$auth->pc();$r=$db->one("SELECT id,original_name AS name,size_bytes AS size,mime_type AS mime FROM transfer_files WHERE pc_id=? AND direction='IPHONE_TO_PC' AND status='READY' ORDER BY created_at LIMIT 1",[$pc['id']]);Util::out(['ok'=>true,'pending'=>(bool)$r,'file'=>$r?:null]);}
if($method==='GET'&&preg_match('#^/v1/files/pc-download/([^/]+)$#',$path,$m)){$pc=$auth->pc();$r=$db->one("SELECT * FROM transfer_files WHERE id=? AND pc_id=? AND direction='IPHONE_TO_PC' AND status='READY'",[$m[1],$pc['id']]);if(!$r){http_response_code(404);exit;}$f=transferPath($r['stored_name']);if(!is_file($f)){http_response_code(404);exit;}header('Content-Type: application/octet-stream');header('X-FaceUnlock-Filename: '.rawurlencode($r['original_name']));readfile($f);@unlink($f);$db->exec("DELETE FROM transfer_files WHERE id=?",[$r['id']]);exit;}
Util::error('ROUTE_NOT_FOUND',404);
