<?php
declare(strict_types=1);
/* FaceUnlock Hosting V2: logical requests, scoped pairings, and compatibility fields. */
$configPath=dirname(__DIR__).'/config.php'; if(!is_file($configPath)){http_response_code(500);exit('Missing hosting/config.php');}$config=require $configPath;
set_exception_handler(static function(Throwable $e): never { error_log('FaceUnlock request failure: '.get_class($e)); Util::out(['ok'=>false,'error'=>['code'=>'SERVER_UNAVAILABLE','message'=>'Request could not be processed']],503); });
foreach(['Util','Database','Auth','Crypto','ApprovalLink','TelegramClient','AuditLog','RateLimiter','Admin'] as $f)require dirname(__DIR__).'/src/'.$f.'.php';
$db=new Database($config['db']);$auth=new Auth($db);$audit=new AuditLog($db);$rate=new RateLimiter($db,$audit,$config['rate_limits']??[]);$telegram=new TelegramClient($config['telegram']??[]);
$method=$_SERVER['REQUEST_METHOD'];$path=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH)?:'/';foreach(['/v1/','/health','/u/','/admin'] as $prefix){if(($i=strpos($path,$prefix))!==false){$path=substr($path,$i);break;}}
function headerSecurity():void{header('X-Content-Type-Options: nosniff');header('Referrer-Policy: no-referrer');header("Content-Security-Policy: default-src 'self'; style-src 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'");}
function activePairing(Database $db,string $pc,string $device):?array{return $db->one("SELECT * FROM pc_device_pairings WHERE pc_id=? AND device_id=? AND status='ACTIVE'",[$pc,$device]);}
function expire(Database $db,string $id):void{$db->exec("UPDATE unlock_requests SET status='EXPIRED',completed_at=NOW() WHERE id=? AND status='PENDING' AND expires_at<?",[$id,time()]);}
function auditCleanup(Database $db,array $cfg):void{if(random_int(1,100)!==1)return;$db->exec("UPDATE unlock_requests SET status='EXPIRED',completed_at=NOW() WHERE status='PENDING' AND expires_at<?",[time()]);$db->exec('DELETE FROM rate_limit_events WHERE created_at < DATE_SUB(NOW(),INTERVAL ? SECOND)',[(int)($cfg['cleanup']['rate_limit_retention_seconds']??86400)]);}
auditCleanup($db,$config);
if($method==='GET'&&$path==='/health'){try{$version=$db->one('SELECT MAX(version) version FROM schema_migrations')['version']??null;Util::out(['ok'=>true,'status'=>'healthy','database'=>'ok','schema_version'=>$version,'application_version'=>'hosting-v2']);}catch(Throwable){Util::out(['ok'=>false,'status'=>'degraded','database'=>'unavailable'],503);}}
if(str_starts_with($path,'/admin'))(new Admin($db,$audit,$rate,$telegram,$config))->handle($method,$path);

// Opaque URL locates a request only; app/device authentication is still mandatory to approve.
if($method==='GET'&&preg_match('#^/u/([^/]+)$#',$path,$m)){$rate->check('approval_link');$token=rawurldecode($m[1]);$r=ApprovalLink::isValidToken($token)?$db->one('SELECT r.*,p.name pc_name FROM unlock_requests r JOIN pcs p ON p.id=r.pc_id WHERE r.approval_token_hash=?',[ApprovalLink::hashToken($token)]):null;unset($token);headerSecurity();header('Cache-Control: no-store');if(!$r){http_response_code(404);exit('<h2>FaceUnlock</h2><p>Invalid or expired request.</p>');}expire($db,$r['id']);$r=$db->one('SELECT r.*,p.name pc_name FROM unlock_requests r JOIN pcs p ON p.id=r.pc_id WHERE r.id=?',[$r['id']]);if($r['status']!=='PENDING'){http_response_code(410);exit('<h2>FaceUnlock</h2><p>Request is no longer pending.</p>');}$url='faceunlock://session?id='.rawurlencode($r['id']);$safe=htmlspecialchars($url,ENT_QUOTES,'UTF-8');$pc=htmlspecialchars($r['pc_name'],ENT_QUOTES,'UTF-8');echo "<!doctype html><title>FaceUnlock</title><meta name=viewport content='width=device-width'><body><h2>FaceUnlock</h2><p>Unlock request: <b>$pc</b></p><a href='$safe'>Open FaceUnlock</a><script>location.replace(".json_encode($url).")</script></body>";exit;}

if($method==='POST'&&$path==='/v1/pair/start'){$rate->check('pair_start');$b=Util::jsonBody();foreach(['pc_id','pc_name','pc_public_key_pem']as$k)if(empty($b[$k]))Util::error('MISSING_'.$k);if(!Util::validId((string)$b['pc_id']))Util::error('INVALID_PC_ID');$token=Util::token();$id=Util::id();$code=str_pad((string)random_int(0,999999),6,'0',STR_PAD_LEFT);$exp=time()+($config['pair_ttl']??600);$db->transaction(function()use($db,$b,$token,$id,$code,$exp){$db->exec('INSERT INTO pcs(id,name,public_key_pem,token_hash)VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE name=VALUES(name),public_key_pem=VALUES(public_key_pem),token_hash=VALUES(token_hash)',[$b['pc_id'],mb_substr($b['pc_name'],0,255),$b['pc_public_key_pem'],hash('sha256',$token)]);$db->exec('INSERT INTO pairings(id,pc_id,pair_code,expires_at)VALUES(?,?,?,?)',[$id,$b['pc_id'],$code,$exp]);});$audit->write('PAIR_STARTED','OK',(string)$b['pc_id']);Util::out(['ok'=>true,'pair_id'=>$id,'pair_code'=>$code,'expires_at'=>$exp,'pc_token'=>$token,'capabilities'=>['multi_device_v2'=>true]]);}

if($method==='POST'&&$path==='/v1/pair/complete'){$rate->check('pair_complete');$b=Util::jsonBody();foreach(['pair_id','pair_code','iphone_name','iphone_public_key_pem']as$k)if(empty($b[$k]))Util::error('MISSING_'.$k);$out=$db->transaction(function()use($db,$b){$pair=$db->one('SELECT x.*,p.name pc_name,p.public_key_pem pc_public_key_pem FROM pairings x JOIN pcs p ON p.id=x.pc_id WHERE x.id=? FOR UPDATE',[$b['pair_id']]);if(!$pair||!hash_equals($pair['pair_code'],(string)$b['pair_code'])||(int)$pair['expires_at']<time()||$pair['completed_device_id'])Util::error('INVALID_OR_EXPIRED_PAIR',403);$stable=hash('sha256','key:'.$b['iphone_public_key_pem']);$device=$db->one('SELECT * FROM devices WHERE stable_identity=? FOR UPDATE',[$stable]);$newToken=null;if(!$device){$newToken=Util::token();$device=['id'=>Util::id(),'token_hash'=>hash('sha256',$newToken)];$db->exec('INSERT INTO devices(id,stable_identity,name,public_key_pem,apns_token,token_hash)VALUES(?,?,?,?,?,?)',[$device['id'],$stable,mb_substr($b['iphone_name'],0,255),$b['iphone_public_key_pem'],(string)($b['apns_token']??''),$device['token_hash']]);}else{$db->exec('UPDATE devices SET name=?,public_key_pem=?,revoked_globally_at=NULL,last_seen_at=NOW() WHERE id=?',[mb_substr($b['iphone_name'],0,255),$b['iphone_public_key_pem'],$device['id']]);}$db->exec("INSERT INTO pc_device_pairings(id,pc_id,device_id,status,paired_at,revoked_at)VALUES(?,?,?,'ACTIVE',NOW(),NULL) ON DUPLICATE KEY UPDATE status='ACTIVE',revoked_at=NULL",[Util::id(),$pair['pc_id'],$device['id']]);$db->exec('UPDATE pairings SET completed_device_id=? WHERE id=?',[$device['id'],$pair['id']]);return ['pair'=>$pair,'device'=>$device,'token'=>$newToken];});$audit->write('PAIR_COMPLETED','OK',$out['pair']['pc_id'],$out['device']['id']);Util::out(['ok'=>true,'device_id'=>$out['device']['id'],'device_api_token'=>$out['token'],'pc_id'=>$out['pair']['pc_id'],'pc_name'=>$out['pair']['pc_name'],'pc_public_key_pem'=>$out['pair']['pc_public_key_pem'],'reused_global_device'=>$out['token']===null]);}

if($method==='GET'&&preg_match('#^/v1/pair/status/([^/]+)$#',$path,$m)){$pc=$auth->pc();$p=$db->one('SELECT * FROM pairings WHERE id=? AND pc_id=?',[$m[1],$pc['id']]);if(!$p)Util::error('NOT_FOUND',404);$d=$p['completed_device_id']?$db->one('SELECT id,name,public_key_pem FROM devices WHERE id=?',[$p['completed_device_id']]):null;Util::out(['ok'=>true,'paired'=>(bool)$d,'device'=>$d]);}

if($method==='GET'&&$path==='/v1/devices'){$pc=$auth->pc();$rows=$db->pdo->prepare("SELECT d.id,d.name,d.last_seen_at,x.nickname,x.status,x.paired_at,x.last_used_at FROM pc_device_pairings x JOIN devices d ON d.id=x.device_id WHERE x.pc_id=? ORDER BY x.status,x.paired_at DESC");$rows->execute([$pc['id']]);Util::out(['ok'=>true,'devices'=>$rows->fetchAll()]);}
if($method==='GET'&&$path==='/v1/device/pcs'){$dev=$auth->device();$s=$db->pdo->prepare("SELECT p.id,p.name,p.last_seen_at,x.nickname,x.status,x.paired_at,x.last_used_at FROM pc_device_pairings x JOIN pcs p ON p.id=x.pc_id WHERE x.device_id=? ORDER BY x.status,x.paired_at DESC");$s->execute([$dev['id']]);Util::out(['ok'=>true,'pcs'=>$s->fetchAll()]);}
if($method==='POST'&&preg_match('#^/v1/devices/([^/]+)/(revoke|rename)$#',$path,$m)){$pc=$auth->pc();$rate->check('revoke',$pc['id']);$id=rawurldecode($m[1]);if(!activePairing($db,$pc['id'],$id))Util::error('PAIRING_NOT_FOUND',404);if($m[2]==='revoke'){$db->exec("UPDATE pc_device_pairings SET status='REVOKED',revoked_at=NOW() WHERE pc_id=? AND device_id=?",[$pc['id'],$id]);$audit->write('PAIR_REVOKED','OK',$pc['id'],$id);Util::out(['ok'=>true,'revoked'=>true,'device_id'=>$id]);}$b=Util::jsonBody();$db->exec('UPDATE pc_device_pairings SET nickname=? WHERE pc_id=? AND device_id=?',[mb_substr((string)($b['nickname']??''),0,255),$pc['id'],$id]);Util::out(['ok'=>true]);}

if($method==='POST'&&$path==='/v1/unlock/request'){$pc=$auth->pc();$rate->check('unlock_request',$pc['id']);$b=Util::jsonBody();$candidates=$db->pdo->prepare("SELECT d.* FROM pc_device_pairings x JOIN devices d ON d.id=x.device_id WHERE x.pc_id=? AND x.status='ACTIVE' AND d.revoked_globally_at IS NULL");$candidates->execute([$pc['id']]);$devices=$candidates->fetchAll();if(!$devices)Util::error('NO_PAIRED_DEVICE',409);$id=Util::id();$challenge=Util::token(32);$raw=ApprovalLink::createToken();$hash=ApprovalLink::hashToken($raw);$exp=time()+($config['unlock_ttl']??90);$db->transaction(function()use($db,$id,$pc,$challenge,$hash,$exp,$devices){$db->exec('INSERT INTO unlock_requests(id,pc_id,challenge,approval_token_hash,expires_at)VALUES(?,?,?,?,?)',[$id,$pc['id'],$challenge,$hash,$exp]);foreach($devices as$d)$db->exec('INSERT INTO unlock_request_candidates(request_id,device_id,notified_at)VALUES(?,?,NOW())',[$id,$d['id']]);});$sent=false;$err=null;try{$telegram->sendUnlockNotification($pc['name'],ApprovalLink::buildUrl((string)($config['base_url']??''),$raw),$exp);$sent=true;}catch(Throwable $e){$err='notification_failed';$audit->write('NOTIFICATION_FAILED','ERROR',$pc['id'],null,$id);}unset($raw,$hash);$audit->write('UNLOCK_REQUESTED','OK',$pc['id'],null,$id,['candidate_count'=>count($devices)]);Util::out(['ok'=>true,'session_id'=>$id,'request_id'=>$id,'challenge'=>$challenge,'expires_at'=>$exp,'device_id'=>$devices[0]['id'],'candidate_device_ids'=>array_column($devices,'id'),'notification_provider'=>'telegram','notification_sent'=>$sent,'notification_error'=>$err,'capabilities'=>['multi_device_v2'=>true]]);}

if($method==='GET'&&$path==='/v1/unlock/pending'){$dev=$auth->device();$s=$db->one("SELECT r.id FROM unlock_requests r JOIN unlock_request_candidates c ON c.request_id=r.id JOIN pc_device_pairings x ON x.pc_id=r.pc_id AND x.device_id=c.device_id WHERE c.device_id=? AND c.state='PENDING' AND x.status='ACTIVE' AND r.status='PENDING' AND r.expires_at>=? ORDER BY r.created_at DESC LIMIT 1",[$dev['id'],time()]);if($s)$db->exec('UPDATE unlock_request_candidates SET seen_at=COALESCE(seen_at,NOW()) WHERE request_id=? AND device_id=?',[$s['id'],$dev['id']]);Util::out(['ok'=>true,'pending'=>(bool)$s,'session_id'=>$s['id']??null,'request_id'=>$s['id']??null]);}

if($method==='GET'&&preg_match('#^/v1/unlock/session/([^/]+)$#',$path,$m)){$dev=$auth->device();$s=$db->one("SELECT r.*,p.name pc_name FROM unlock_requests r JOIN pcs p ON p.id=r.pc_id JOIN unlock_request_candidates c ON c.request_id=r.id WHERE r.id=? AND c.device_id=?",[$m[1],$dev['id']]);if(!$s||!activePairing($db,$s['pc_id'],$dev['id']))Util::error('NOT_FOUND',404);expire($db,$s['id']);$s=$db->one('SELECT r.*,p.name pc_name FROM unlock_requests r JOIN pcs p ON p.id=r.pc_id WHERE r.id=?',[$s['id']]);Util::out(['session_id'=>$s['id'],'request_id'=>$s['id'],'challenge'=>$s['challenge'],'pc_id'=>$s['pc_id'],'pc_name'=>$s['pc_name'],'expires_at'=>(int)$s['expires_at'],'status'=>$s['status']]);}

if($method==='POST'&&preg_match('#^/v1/unlock/approve/([^/]+)$#',$path,$m)){
 $dev=$auth->device();$rate->check('approval',$dev['id']);$b=Util::jsonBody();$s=$db->one("SELECT r.* FROM unlock_requests r JOIN unlock_request_candidates c ON c.request_id=r.id WHERE r.id=? AND c.device_id=?",[$m[1],$dev['id']]);
 if(!$s||!activePairing($db,$s['pc_id'],$dev['id'])){$audit->write('UNLOCK_REJECTED','DENIED',null,$dev['id'],$m[1]);Util::error('PAIRING_REVOKED',403);}
 if(empty($b['signature'])||strlen((string)$b['signature'])>16384||!Crypto::verify($dev['public_key_pem'],Util::canonical($s),(string)$b['signature']))Util::error('BAD_SIGNATURE',403);
 $win=$db->transaction(function()use($db,$s,$dev,$b){
   $biometric=(string)($b['biometric']??'faceid');
   $changed=$db->exec("UPDATE unlock_requests SET status='APPROVED',winning_device_id=?,winning_transport=?,signature_b64=?,biometric=?,approved_at=NOW(),completed_at=NOW() WHERE id=? AND status='PENDING' AND expires_at>=?",[$dev['id'],'online',$b['signature'],$biometric,$s['id'],time()]);
   if($changed!==1)return false;
   $db->exec("UPDATE unlock_request_candidates SET state=IF(device_id=?,'APPROVED','LATE'),responded_at=NOW() WHERE request_id=?",[$dev['id'],$s['id']]);
   $db->exec("UPDATE pc_device_pairings SET last_used_at=NOW() WHERE pc_id=? AND device_id=?",[$s['pc_id'],$dev['id']]);$db->exec('UPDATE devices SET last_seen_at=NOW() WHERE id=?',[$dev['id']]);return true;
 });
 if(!$win){$audit->write('APPROVAL_REPLAY','DENIED',$s['pc_id'],$dev['id'],$s['id']);Util::error('ALREADY_COMPLETED',409);}
 $audit->write('UNLOCK_APPROVED','OK',$s['pc_id'],$dev['id'],$s['id']);Util::out(['ok'=>true,'winner'=>true,'winning_device_id'=>$dev['id']]);
}

if($method==='POST'&&preg_match('#^/v1/unlock/reject/([^/]+)$#',$path,$m)){$dev=$auth->device();$db->exec("UPDATE unlock_request_candidates SET state='REJECTED',responded_at=NOW() WHERE request_id=? AND device_id=? AND state='PENDING'",[$m[1],$dev['id']]);Util::out(['ok'=>true]);}
if($method==='GET'&&preg_match('#^/v1/unlock/status/([^/]+)$#',$path,$m)){$pc=$auth->pc();$s=$db->one('SELECT r.*,d.public_key_pem device_public_key_pem FROM unlock_requests r LEFT JOIN devices d ON d.id=r.winning_device_id WHERE r.id=? AND r.pc_id=?',[$m[1],$pc['id']]);if(!$s)Util::error('NOT_FOUND',404);expire($db,$s['id']);$s=$db->one('SELECT r.*,d.public_key_pem device_public_key_pem FROM unlock_requests r LEFT JOIN devices d ON d.id=r.winning_device_id WHERE r.id=?',[$s['id']]);Util::out(['ok'=>true,'session_id'=>$s['id'],'request_id'=>$s['id'],'status'=>$s['status'],'challenge'=>$s['challenge'],'expires_at'=>(int)$s['expires_at'],'signature'=>$s['signature_b64'],'winning_device_id'=>$s['winning_device_id'],'device_public_key_pem'=>$s['device_public_key_pem']]);}
Util::error('ROUTE_NOT_FOUND',404);
