<?php
declare(strict_types=1);session_start();$config=require dirname(__DIR__).'/config.php';foreach(['Util','Database'] as $f)require dirname(__DIR__).'/src/'.$f.'.php';$db=new Database($config['db']);
function paired(Database $db,string $pc,string $dev):bool{return(bool)$db->one("SELECT id FROM pc_device_pairings WHERE pc_id=? AND device_id=? AND status='ACTIVE'",[$pc,$dev]);}
$pc=(string)($_GET['pc']??$_SESSION['transfer_pc']??'');$mode=(string)($_GET['mode']??$_SESSION['transfer_mode']??'pc');$token=(string)($_GET['token']??'');
if($token!==''&&$pc!==''){$hash=hash('sha256',$token);if($mode==='iphone'){$d=$db->one('SELECT id FROM devices WHERE token_hash=? AND revoked_globally_at IS NULL',[$hash]);if($d&&paired($db,$pc,$d['id'])){$_SESSION['transfer_ok']=true;$_SESSION['transfer_pc']=$pc;$_SESSION['transfer_mode']='iphone';$_SESSION['transfer_device']=$d['id'];header('Location: transfer.php');exit;}}else{$p=$db->one('SELECT id FROM pcs WHERE id=? AND token_hash=?',[$pc,$hash]);if($p){$_SESSION['transfer_ok']=true;$_SESSION['transfer_pc']=$pc;$_SESSION['transfer_mode']='pc';header('Location: transfer.php');exit;}}}
if(empty($_SESSION['transfer_ok'])||!$pc){http_response_code(401);?><!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{font:16px system-ui;background:#111;color:#eee;padding:30px}input,button{padding:12px;margin:6px;background:#222;color:#fff;border:1px solid #555;border-radius:8px}</style><h2>FaceUnlock File Upload</h2><p>Open this page from FaceUnlock Agent or the iPhone app.</p><?php exit;}
$direction=$mode==='iphone'?'IPHONE_TO_PC':'PC_TO_IPHONE';$dir=dirname(__DIR__).'/storage/transfers';if(!is_dir($dir))mkdir($dir,0700,true);$message='';
if($_SERVER['REQUEST_METHOD']==='POST'&&!empty($_FILES['files'])){$names=$_FILES['files']['name'];if(!is_array($names))$names=[$names];foreach($names as $i=>$name){$tmp=is_array($_FILES['files']['tmp_name'])?$_FILES['files']['tmp_name'][$i]:$_FILES['files']['tmp_name'];$err=is_array($_FILES['files']['error'])?$_FILES['files']['error'][$i]:$_FILES['files']['error'];if($err!==UPLOAD_ERR_OK||!is_uploaded_file($tmp))continue;$safe=basename((string)$name);$id=bin2hex(random_bytes(16));$stored=$id.'.bin';if(!move_uploaded_file($tmp,$dir.'/'.$stored))continue;$size=filesize($dir.'/'.$stored);$mime=(new finfo(FILEINFO_MIME_TYPE))->file($dir.'/'.$stored)?:'application/octet-stream';$device=$mode==='iphone'?($_SESSION['transfer_device']??null):null;$db->exec("INSERT INTO transfer_files(id,pc_id,device_id,direction,original_name,stored_name,size_bytes,mime_type)VALUES(?,?,?,?,?,?,?,?)",[$id,$pc,$device,$direction,$safe,$stored,$size,$mime]);}$message='Upload complete.';}
?><!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><title>FaceUnlock Upload</title><style>body{margin:0;background:#111315;color:#eee;font:15px system-ui}.box{max-width:900px;margin:30px auto;background:#191b1e;border:1px solid #45484d;border-radius:14px;padding:22px}.drop{border:2px dashed #555;border-radius:12px;min-height:330px;display:flex;align-items:center;justify-content:center;flex-direction:column}.green{background:#169b45;color:white;border:0;border-radius:7px;padding:11px 18px;font-weight:600}input{margin:15px}.hint{color:#999;font-size:26px}.ok{color:#69d58a}</style></head><body><div class="box"><h2>Upload File</h2><?php if($message):?><p class="ok"><?=htmlspecialchars($message)?></p><?php endif?><form method="post" enctype="multipart/form-data"><div class="drop"><div class="hint">Please drag the files here</div><input id="files" type="file" name="files[]" multiple><button class="green" type="submit">Confirm Upload</button></div></form><p><?= $mode==='iphone'?'Files will be downloaded by your paired PC.':'Files stay here until the iPhone downloads or deletes them.' ?></p></div></body></html>
